FROM mcr.microsoft.com/windows/servercore:ltsc2022

RUN Install-WindowsFeature -Name RemoteDesktop

RUN Set-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\WinStations\RDP-Tcp' -Name PortNumber -Type DWORD -Value 3390

RUN New-Item -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\WinStations\RDP-Tcp' -Name SecurityLayer -Type DWORD -Value 1

RUN New-Item -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\WinStations\RDP-Tcp' -Name AllowOnlyNLA -Type DWORD -Value 0

RUN Set-Service -Name "Remote Desktop Services" -StartupType Automatic

RUN Start-Service "Remote Desktop Services"

EXPOSE 3390

CMD ["mstsc", "/v:localhost:3389"]
